services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/work
    working_dir: /work
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
