SHELL := /bin/bash

# Device configuration (override via .env or environment)
USB_DEVICE ?= /dev/ttyACM0
MPREMOTE_DEVICE ?= a0

# Directories
SRC_DIR := src
DIST_DIR := dist
TOOLS_DIR := tools
LIB_DIR := lib

# Template compilation
TEMPLATE_DIR := $(SRC_DIR)/www/_uwifisetup
TEMPLATE_NAMES := welcome list_networks try_connect complete

# Source .py files (library + generated template .py files)
LIB_PY_FILES := $(shell find $(SRC_DIR)/uwifisetup -name "*.py" -type f)
LIB_MPY_FILES := $(patsubst $(SRC_DIR)/%.py,$(DIST_DIR)/%.mpy,$(LIB_PY_FILES))

# Template .mpy files (generated from HTML -> .py -> .mpy)
TEMPLATE_MPY_FILES := $(addprefix $(DIST_DIR)/www/_uwifisetup/,$(addsuffix _html.mpy,$(TEMPLATE_NAMES)))

# Test files
ALL_TESTS := $(wildcard tests/test_*.py)

# Tools
DOCKER ?= docker
DC := $(DOCKER) compose --project-directory $(CURDIR)

# Host UID/GID for chown of build artifacts
UID ?= 1000
GID ?= 100

# ==============================================================================
# Internal targets (run inside container)
# ==============================================================================

.PHONY: _build _clean _compile_templates _compile_mpy _lint _typecheck _etest _htest _validate

_build: _compile_mpy
	@chown -R $(UID):$(GID) $(DIST_DIR)

_clean:
	rm -f $(TEMPLATE_DIR)/*.py
	rm -rf $(DIST_DIR)/*

_compile_templates:
	@cd $(SRC_DIR)/www && for t in $(TEMPLATE_NAMES); do \
		python ../../$(LIB_DIR)/utemplate/utemplate_util.py compile _uwifisetup/$$t.html || true; \
	done; \
	echo -e "\\033[0;32m *** Compiling templates — ModuleNotFoundError above is expected and harmless *** \\033[0m"

_compile_mpy: _compile_templates $(LIB_MPY_FILES) $(TEMPLATE_MPY_FILES)
	@chown -R $(UID):$(GID) $(DIST_DIR)

# Pattern rule: compile .py -> .mpy using mpy-cross
$(DIST_DIR)/%.mpy: $(SRC_DIR)/%.py
	@mkdir -p $(@D)
	@mpy-cross -v -s $* $< -o $@

# Template .mpy depends on template .py (generated by _compile_templates)
$(DIST_DIR)/www/_uwifisetup/%_html.mpy: $(TEMPLATE_DIR)/%_html.py
	@mkdir -p $(@D)
	@mpy-cross -v -s $* $< -o $@

$(TEMPLATE_DIR)/%_html.py: $(TEMPLATE_DIR)/%.html
	@cd $(SRC_DIR)/www && python ../../$(LIB_DIR)/utemplate/utemplate_util.py compile _uwifisetup/$*.html || true

_lint:
	flake8 src/uwifisetup

_typecheck:
	python -m mypy src/uwifisetup --check-untyped-defs

_etest:
	@for f in $(filter-out tests/test_wifi.py,$(ALL_TESTS)); do \
		echo "=== Emulator (src): $$f ==="; \
		micropython $$f src || exit 1; \
	done
	@for f in $(filter-out tests/test_wifi.py,$(ALL_TESTS)); do \
		echo "=== Emulator (dist): $$f ==="; \
		micropython $$f dist || exit 1; \
	done

_htest: _mppush_raw _deploy_deps
	mpremote $(MPREMOTE_DEVICE) mip install unittest
	mpremote $(MPREMOTE_DEVICE) exec "import os; os.mkdir('/tmp')"
	@for f in $(ALL_TESTS); do \
		echo "=== Device: $$f ==="; \
		mpremote $(MPREMOTE_DEVICE) run $$f || exit 1; \
	done

_validate:
	@HASH1=$$(find $(DIST_DIR) -type f | sort | xargs sha256sum); \
	$(MAKE) _clean; \
	$(MAKE) _build; \
	HASH2=$$(find $(DIST_DIR) -type f | sort | xargs sha256sum); \
	if [ "$$HASH1" != "$$HASH2" ]; then \
		echo "Re-Build of dist folder produced different hash. Did you forget to pre-build?"; \
		exit 1; \
	fi; \
	echo "Hash Values match. dist looks good"

# ==============================================================================
# Device targets (run inside container)
# ==============================================================================

.PHONY: _mppush _mppush_raw _deploy_deps _mpclean _mpls _mprepl _mprshell _mprun _mpreset _blescan _bleuart

_mppush: _build
	rshell -p $(USB_DEVICE) "rsync $(DIST_DIR)/uwifisetup /pyboard/lib/uwifisetup"
	rshell -p $(USB_DEVICE) "rsync $(DIST_DIR)/www /pyboard/lib/uwifisetup/www"
	rshell -p $(USB_DEVICE) "rsync $(SRC_DIR)/www/_uwifisetup/assets /pyboard/lib/uwifisetup/www/_uwifisetup/assets"

_mppush_raw:
	rshell -p $(USB_DEVICE) "rsync $(SRC_DIR)/uwifisetup/ /pyboard/lib/uwifisetup"
	rshell -p $(USB_DEVICE) "rsync $(SRC_DIR)/www /pyboard/lib/uwifisetup/www"

_deploy_deps:
	mpremote mip install github:shaneapowell/upython-wifi-setup/package-deps.json
	mpremote mip install aioble

_mpclean:
	rshell -p $(USB_DEVICE) "rm -r /pyboard/*"

_mpls:
	rshell -p $(USB_DEVICE) "ls -l /pyboard"

_mprepl:
	mpremote $(MPREMOTE_DEVICE) repl

_mprshell:
	rshell -p $(USB_DEVICE)

_mprun:
ifeq ($(origin FILE),undefined)
	$(error Usage: make _mprun FILE=<filename>)
endif
	mpremote $(MPREMOTE_DEVICE) run examples/$(FILE)

_mpreset:
	mpremote $(MPREMOTE_DEVICE) reset

_blescan:
	ble-scan

_bleuart:
ifeq ($(origin MAC),undefined)
	$(error Usage: make _bleuart MAC=<mac_address>)
endif
	python3 tools/ble-uart-term.py $(MAC)

# ==============================================================================
# Docker wrapper targets (run outside container)
# ==============================================================================

.PHONY: up down build clean lint typecheck test etest htest validate deploy deploy_raw deploy_deps mpclean mpls mprepl mpshell mprun mpreset run_example run_example_ble run_example_reset shell ble-scan ble-uart scorched-earth

up:
	@$(DC) up -d dev

down:
	@$(DC) down

build: up
	@$(DC) exec dev make _clean
	@$(DC) exec dev make _build UID=$(shell id -u) GID=$(shell id -g)

clean: up
	@$(DC) exec dev make _clean

lint: up
	@$(DC) exec dev make _lint

typecheck: up
	@$(DC) exec dev make _typecheck

test:
	@read -p "Run which tests? (e)mulator / (h)ardware [e]: " choice; \
	case "$$choice" in \
		h|H) $(MAKE) htest ;; \
		*)   $(MAKE) etest ;; \
	esac

etest: up
	@$(DC) exec dev make _etest

htest: up
	@$(DC) exec dev make _htest

validate: up
	@$(DC) exec dev make _validate

deploy: up
	@$(DC) exec dev make _mppush

deploy_raw: up
	@$(DC) exec dev make _mppush_raw

deploy_deps: up
	@$(DC) exec dev make _deploy_deps

mpclean: up
	@$(DC) exec dev make _mpclean

mpls: up
	@$(DC) exec dev make _mpls

mprepl: up
	@$(DC) exec -it dev make _mprepl

mpshell: up
	@$(DC) exec -it dev make _mprshell

mprun: up
	@$(DC) exec dev make _mprun FILE=$(FILE)

mpreset: up
	@$(DC) exec dev make _mpreset

run_example: up
	@$(DC) exec dev make _mprun FILE=example.py

run_example_ble: up
	@$(DC) exec dev make _mprun FILE=example_ble.py

run_example_reset: up
	@$(DC) exec dev make _mprun FILE=example_reset.py

shell: up
	@$(DC) exec -it dev bash

ble-scan: up
	@$(DC) exec -it dev make _blescan

ble-uart: up
	@$(DC) exec -it dev make _bleuart MAC=$(MAC)

scorched-earth: clean down
	@$(DC) rm -f
	@docker image rm $(shell $(DC) config --images 2>/dev/null) 2>/dev/null || true
