name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-and-typecheck:
    name: lint-and-typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - run: docker compose up -d dev
      - run: docker compose exec dev make _lint
      - run: docker compose exec dev make _typecheck
      - run: docker compose down

  verify-dist:
    name: verify-dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - run: docker compose up -d dev
      - run: docker compose exec dev make _validate
      - run: docker compose down
