
name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-and-typecheck:
    name: lint-and-typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "=3.11"
      - run: python -m pip install --upgrade pip wheel
      - run: pip install pipenv
      - run: pipenv sync
      - run: pipenv run linter
      - run: pipenv run typechecker
